[package]
name = "mixnet"
edition = "2021"
rust-version = "1.56.1"
description = "Mixnet protocol for libp2p"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/paritytech/substrate"
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
instant = "0.1.12"
libp2p-core = { version = "0.34", default-features = false }
libp2p-swarm = "0.37"
log = "0.4.17"
rand = "0.8.4"
rand_distr = "0.4.3"
void = "1.0"
blake2-rfc = { version = "0.2.18", default-features = false }
curve25519-dalek = "3.2.0"
dyn-clone = "1.0.5"
static_assertions = "1.1.0"

#sphinx deps
x25519-dalek = "1.1.0"
aes = "0.8.1"
ctr = "0.9.1"
sha2 = "0.10.2"
hkdf = "0.12.3"
hmac = "0.12.1"
lioness = "0.1.2"
arrayref = "0.3.6"
subtle = "2.4.1"

[dev-dependencies]
async-std = "1.11"
libp2p-tcp = "0.34.0"
libp2p-noise = "0.37.0"
libp2p-yamux = "0.38.0"
libp2p-mplex = "0.34.0"
env_logger = "0.9.0"
ed25519-zebra = "3.0.0"
rand = { version = "0.8.4", features = ["small_rng"] }
